apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: person-service
  title: Person Service
  description: Person Service
  tags:
    - java
    - container-app
spec:
  type: service
  owner: team-person
  lifecycle: experimental
  providesApis:
    - person-api
  dependsOn:
    - resource:default/azure-lz-2
    - resource:default/database-person
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: person-api
  title: Person API
  description: Person API
  tags:
    - REST
spec:
  type: openapi
  owner: team-person
  lifecycle: experimental
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Artist API
      license:
        name: MIT
    servers:
      - url: http://artist.spotify.net/v1
    paths:
      /artists:
        get:
          summary: List all artists
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: database-person
  title: Person Database
  description: Database for Person
  tags:
    - postgres
spec:
  type: database
  owner: team-person
  lifecycle: experimental
  dependsOn:
    - resource:default/azure-lz-2